### ISSUE TITLE
question on the jacobian for log(a/b), log(b)

### ISSUE THREAD

**Issue by arcolombo** [paulnorthrop/bang#2]
for p(u,v) = p(h1(u,v), h2(u,v)) |J( d(a,b)/du,v)|

where u = log(a/b), v= log(b) we would need to find the inverse functions of   log(a,b)  denoted here as h1(u,v), and h2(u,v)   and then for the jacobian we need the partials of   h1(u,v)/d(u,v)  and similar for h2.

however because the derivatives of log(a/b) and log(b) are easier with respect to a,b  as opposed to inverses,   the jacobian d(u,v)/d(a,b) is 1/ab.

but we need to take the inverse of the jacobian  = (ab)

which is what they did in the Gelman book  equation 5.10    so the log of jacobian is  log(a)+lob(b)  but in yoru functions the jacobian is negative?  why?  

thank you!!!

**Comment by paulnorthrop** [comment]
The bang package calls the function rust::ru() in my rust package to perform the simulation. The code for the transformation part of this function is based on the inverse transformation function and its jacobian, hence the difference that you observed.

**Comment by paulnorthrop** [comment]
Closed for the moment, but please do reopen if my reply did not help, or was not correct.
